name: UUIDProvider
main: net.kaikk.mc.uuidprovider.UUIDProvider
version: 1.3.1
author: KaiNoMood
authors: MrWisski
description: Provides UUID resolution services to other plugins, as well as a fast cache and mySQL Storage of data.
website: https://github.com/KaiKikuchi/UUIDProvider
load: STARTUP

commands:
   uuidprovider:
      description: UUIDProvider commands